# # Swell Generation by a Translating Idealized Hurricane
#
# A translating tropical cyclone (TC) is a textbook generator of long-period
# swell.  The salient effects, captured by this example, are:
#
# 1. **Storm-following sea state** beneath the eyewall: locally wind-driven
#    waves with peak phase speeds comparable to the maximum wind.
# 2. **Extended (or "trapped") fetch** on the right-front side of the track
#    (in the northern hemisphere): when the storm translation speed `Uₜ` is
#    close to the group velocity of the dominant waves, those waves stay
#    inside the forcing region for many radii and grow well above what a
#    stationary storm of the same intensity would produce
#    [Bowyer and MacAfee 2005].
# 3. **Far-field swell wake**: low-frequency, narrow-banded long waves that
#    radiate forward and to the right of the storm and persist long after
#    the storm has passed [Young 2003, 2006].
#
# These features are routinely seen in operational hindcasts of major
# hurricanes such as Bonnie [Wright et al. 2001] and Ivan
# [Moon et al. 2003]; see also the fetch-growth analysis in Hwang [2016].
#
# Following the WAVEWATCH III operational practice we use:
#
# - **Wind input**:  Janssen-style quasi-linear pressure-correlation
#   `PressureCorrelationInput` (the ST3 family); a per-grid-point
#   wave-supported-stress cap keeps the wind input below the air-side stress
#   `ρ_a u_*²` (a one-pass approximation to the iterative WW3 τ_w feedback).
# - **Dissipation**:  Local saturation-based whitecapping
#   `LocalSaturationDissipation` (the ST4 family) — dampens cells whose
#   normalized saturation `B(k,θ) = N σ k³` exceeds a threshold `B_r`.
# - **Nonlinear interactions**:  Hasselmann discrete interaction
#   approximation `HasselmannDIA` with bilinear 4-corner spread.
# - **Hurricane wind**:  Holland (1980) parametric profile, translated at
#   constant velocity along an idealized straight track.
#
# References:
# - Holland G.J., 1980. *An analytic model of the wind and pressure profiles
#   in hurricanes.* Mon. Wea. Rev. 108, 1212–1218.
# - Bowyer P. and MacAfee A., 2005. *The Theory of Trapped-Fetch Waves with
#   Tropical Cyclones — An Operational Perspective.* Wea. Forecasting 20,
#   229–244.
# - Young I.R., 2003. *A review of the sea state generated by hurricanes.*
#   Mar. Struct. 16, 201–218.
# - Young I.R., 2006. *Directional spectra of hurricane wind waves.*
#   J. Geophys. Res. 111, C08020.
# - Wright C.W. et al., 2001. *Hurricane directional wave spectrum spatial
#   variation in the open ocean.* J. Phys. Oceanogr. 31, 2472–2488.
# - Moon I.-J. et al., 2003. *Numerical simulation of sea surface directional
#   wave spectra under hurricane wind forcing.* J. Phys. Oceanogr. 33,
#   1680–1706.
# - Hwang P.A., 2016. *Fetch- and duration-limited nature of surface wave
#   growth inside tropical cyclones: With applications to air-sea exchange
#   and remote sensing.* J. Phys. Oceanogr. 46, 41–56.

using Oceananigans, Ripple, CairoMakie
using Printf

Base.include(@__MODULE__, joinpath(@__DIR__, "..", "scripts", "example_visuals.jl"))

output_dir = example_output_directory("translating_hurricane_swell")
plot_paths = String[]

# ## Configuration
#
# Domain: 1500 × 1500 km box, periodic in x, bounded in y.  Resolution
# 25 km in each direction is enough to resolve the eye while keeping the
# integration tractable on a laptop.  Spectral grid: 25 logarithmically
# spaced frequency bins (`XFR=1.1`) crossed with 16 evenly spaced
# directions.

small = example_mode() == :small
Nx = small ? 32 : 60
Ny = small ? 32 : 60
Lx = Ly  = 1.5e6                # m
T_FINAL  = small ? 6 * 3600.0 : 24 * 3600.0   # s
DT       = 60.0                 # s
OUTPUT_DT = 3 * 3600.0          # snapshot interval

NFREQ = 25
NDIR  = 16
f0    = 0.04118
xfr   = 1.1
frequency_centers = [f0 * xfr^(k - 1) for k in 1:NFREQ]
direction_centers = collect(range(0, 2π * (NDIR - 1) / NDIR; length = NDIR))

# Single-level deep-water grid.  Holland-wind hurricane.
grid = RectilinearGrid(CPU();
                       size = (Nx, Ny, 1),
                       halo = (3, 3, 3),
                       x = (0, Lx),
                       y = (0, Ly),
                       z = (-1.0, 0.0),
                       topology = (Periodic, Bounded, Bounded))

cgrid = FrequencyDirectionGrid(; frequency = frequency_centers,
                                 φ         = direction_centers)

# ### Translating Holland (1980) hurricane
#
# `LinearStormTrack` linearly interpolates the storm center between user-
# supplied waypoints.  The track starts on the western edge and translates
# eastward at `U_translation`.  Choice of `U_translation = 7 m/s` is roughly
# the deep-water group velocity for a `f = 0.1 Hz` swell, putting us near
# the extended-fetch resonance condition of Bowyer & MacAfee [2005].

U_translation = 7.0                                # m/s
y_track       = 0.40 * Ly                          # storm passes left-of-center y
track_start   = (0.15 * Lx, y_track)
track_end     = (0.15 * Lx + U_translation * T_FINAL, y_track)
storm_track   = LinearStormTrack([0.0, T_FINAL], [track_start, track_end])

hurricane = HollandHurricaneWind(; center          = storm_track,
                                   vmax            = 50.0,         # m/s peak winds
                                   rmax            = 40.0e3,       # m radius of max wind
                                   radius          = 500.0e3,      # m cutoff
                                   shape_parameter = 1.5,
                                   inflow_angle    = deg2rad(20),
                                   rotation        = Counterclockwise())

# ## Physics
#
# State-of-the-art (within Ripple's ST3/ST4-derived terms): Janssen wind
# input + saturation dissipation + Hasselmann DIA, all coupled via the
# bundle's `prepare_physics` which runs three KernelAbstractions kernels
# per time step.

wind_input  = PressureCorrelationInput(; drag = BulkWindDrag(:linear),
                                         wind = hurricane,
                                         direction = 0.0)              # ignored when wind is a struct
dissipation = LocalSaturationDissipation(; B_r     = 1.05e-2,
                                           σ_power = 1.0)
nonlinear   = HasselmannDIA(; C = 1.5e7)
physics     = MeanSpectrumPhysics(; wind_input, dissipation, nonlinear)

# WENO5 advection is essential here — swell propagates across the basin and
# any numerical diffusion would smear the wake.
model = SpectralWaveModel(; grid,
                            spectral_grid = cgrid,
                            advection     = WENO(),
                            physics,
                            timestepper   = :SemiImplicitEuler)

# Seed at a small uniform action density to spin up.
total_weight = sum(spectral_weight(cgrid, m, n) for m in 1:NFREQ, n in 1:NDIR)
set!(model, N = 1.0e-3 / total_weight)

# ## Time integration
#
# Snapshots every `OUTPUT_DT` of: `H_s` field, peak-frequency map, mean
# direction map.  The animation reveals the trailing swell wake and the
# extended-fetch enhancement on the right side of the track.

times    = Float64[]
hs_snaps = Array{Float64,2}[]
fp_snaps = Array{Float64,2}[]
md_snaps = Array{Float64,2}[]
storm_xy = Tuple{Float64,Float64}[]

push_snapshot!() = begin
    push!(times, model.clock.time)
    Hs = significant_wave_height(model.action)
    fp_field = peak_frequency(model.action)
    md_field = mean_direction(model.action)
    foreach(Oceananigans.compute!, (Hs, fp_field, md_field))
    push!(hs_snaps, Array(interior(Hs)[:, :, 1]))
    push!(fp_snaps, Array(interior(fp_field)[:, :, 1]))
    push!(md_snaps, Array(interior(md_field)[:, :, 1]))
    push!(storm_xy, hurricane.center(model.clock.time))
end

push_snapshot!()
next_output = OUTPUT_DT
while model.clock.time < T_FINAL
    time_step!(model, DT)
    if model.clock.time >= next_output - DT / 2
        push_snapshot!()
        @info "snapshot" t_hours = model.clock.time / 3600 Hs_max = maximum(hs_snaps[end])
        next_output += OUTPUT_DT
    end
end

# ## Plots
#
# Final-time `H_s` map with storm track overlaid.

xs = collect(xnodes(grid)) ./ 1e3   # km
ys = collect(ynodes(grid)) ./ 1e3

fig = Figure(size = (900, 700))
ax  = Axis(fig[1, 1];
           xlabel = "x (km)", ylabel = "y (km)",
           title  = @sprintf("Hs at t = %.1f h, translating hurricane (Vt = %.1f m/s)",
                              times[end] / 3600, U_translation))
hm  = heatmap!(ax, xs, ys, hs_snaps[end]; colormap = :viridis)
Colorbar(fig[1, 2], hm; label = "Hs (m)")
track_xs = [pt[1] / 1e3 for pt in storm_xy]
track_ys = [pt[2] / 1e3 for pt in storm_xy]
lines!(ax, track_xs, track_ys; color = :white, linewidth = 2)
scatter!(ax, [track_xs[end]], [track_ys[end]];
         color = :red, marker = :star5, markersize = 25)
hs_path = joinpath(output_dir, "hs_final.png")
save(hs_path, fig; px_per_unit = 2)
push!(plot_paths, hs_path)

# Snapshot mosaic: Hs at four times.
mosaic = Figure(size = (1200, 900))
ntiles = min(length(hs_snaps), 6)
idxs   = round.(Int, range(1, length(hs_snaps); length = ntiles))
for (ti, idx) in enumerate(idxs)
    r = (ti - 1) ÷ 3 + 1
    c = (ti - 1) % 3 + 1
    ax = Axis(mosaic[r, c];
              xlabel = "x (km)", ylabel = "y (km)",
              title  = @sprintf("t = %.1f h", times[idx] / 3600),
              aspect = DataAspect())
    hm = heatmap!(ax, xs, ys, hs_snaps[idx]; colormap = :viridis,
                  colorrange = (0, maximum(hs_snaps[end])))
    sx, sy = storm_xy[idx]
    scatter!(ax, [sx / 1e3], [sy / 1e3];
             color = :red, marker = :star5, markersize = 18)
end
mosaic_path = joinpath(output_dir, "hs_mosaic.png")
save(mosaic_path, mosaic; px_per_unit = 2)
push!(plot_paths, mosaic_path)

@info "Hurricane swell example done" hs_max = maximum(hs_snaps[end]) outputs = plot_paths
